# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://qxmwrr.github.io
date_format: "ordinal"
title: Mr.Q's Blog
subtitle: "编程是一门技术，更是一门艺术"
description: "Mr.Q's Blog"
keywords: qxmwrr, Qiu ximing, 化作春泥
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Qiu ximing
organization: autohome.com.cn
organization_url: http://www.autohome.com.cn
github_username: qxmwrr
location: Beijing, China
email: qxmwrr@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: Wiki

#  -
#    href: /links/
#    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: qxmwrr/qxmwrr.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: qxmwrr
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: qxmwrr
    repo: blog-comments
    oauth:
        client_id: bdb34a351815de070f24
        client_secret: 16e3681665e317381dbb92db47683169e70a0527
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
